import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import Uploader from "../components/uploader/Uploader";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.kritik.hello.useQuery({ text: "Ahmad" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="text-xl font-bold">
          {`${hello.data ? `Hello, ${hello.data?.greetings}` : "Loading..."}`}
        </div>
        <Uploader />
      </Layout>
    </>
  );
};

export default Home;
